### ISSUE TITLE
UI doesn't show afer downloading previews

### ISSUE THREAD

**Issue by garpunkal** [SebastianMaung/MiyooThemeDownloader#1]
Is this expected behaviour? 

It runs the download scripts and then just exits back to the app menu.

**Comment by SebastianMaung** [comment]
Sorry about that. I have uploaded commits for a working one, but I just downloaded it again after that and it seems to still have a problem. Not sure why it stops working after uploaded to the repo, but the releases tab works for sure. Please try it and let me know if you have any problems.
Edit Nov 22 2023: with help from [schmurtzm](https://www.reddit.com/user/schmurtzm/), I was able to fix the downloading from source issue. It should work now
