### ISSUE TITLE
Only pulling the themes present on the Readme of target location

### ISSUE THREAD

**Issue by Mavarice** [SebastianMaung/MiyooThemeDownloader#4]
Installed this today, and it boots and works fine, but only pulls in 6 themes which are the exact 6 on the Readme
* MiyooCarplay
* Star Wars (Miyoo Be With You)
* sONIONc
* Material (6-pack)
* AnalogPhosphor (3-pack)
* Capcom SNK (Handheld Filter)

Downloading and using those themes works without issue, but only shows those themes.

**Comment by SebastianMaung** [comment]
Oh, I see they changed the format for themes on the readme. I'll get this fixed as soon as possible, shouldn't be too hard

**Comment by SebastianMaung** [comment]
Fixed, thank you for bringing this to my attention with a well detailed issue report
